name: food_delivery_app
description: A food delivery app similar to Swiggy and Zomato.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  google_sign_in: ^6.2.1
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geolocator: ^10.0.0
  flutter_map_location_marker: ^7.0.0
  shared_preferences: ^2.2.2
  geocoding: ^2.1.1
  camera: ^0.10.5
  path_provider: ^2.1.1
  firebase_storage: ^11.6.0
  path: ^1.9.0
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

