// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK1e6ESrZxSIq2zBpt14fm17_YNsUEx2U',
    appId: '1:61462913585:web:5caacbeb445e2480e16b10',
    messagingSenderId: '61462913585',
    projectId: 'food-delivery-app-74e40',
    authDomain: 'food-delivery-app-74e40.firebaseapp.com',
    storageBucket: 'food-delivery-app-74e40.firebasestorage.app',
    measurementId: 'G-XY9N8QLMWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9S2-bQaVgC5JSVOry8CQsnHXbZKVGtfw',
    appId: '1:61462913585:android:af8b89c59174c09de16b10',
    messagingSenderId: '61462913585',
    projectId: 'food-delivery-app-74e40',
    storageBucket: 'food-delivery-app-74e40.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK1e6ESrZxSIq2zBpt14fm17_YNsUEx2U',
    appId: '1:61462913585:web:d5d959d8b0a11489e16b10',
    messagingSenderId: '61462913585',
    projectId: 'food-delivery-app-74e40',
    authDomain: 'food-delivery-app-74e40.firebaseapp.com',
    storageBucket: 'food-delivery-app-74e40.firebasestorage.app',
    measurementId: 'G-8W2GF0GZ90',
  );
}
