import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart'; // Add this import
import 'firebase_options.dart';
import 'screens/onboarding_screen.dart';
import 'screens/home_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Food Delivery App',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF00BFA6),
          primary: const Color(0xFF00BFA6),
        ),
        fontFamily: 'Roboto',
        inputDecorationTheme: InputDecorationTheme(
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: BorderSide.none,
          ),
          filled: true,
          fillColor: Colors.grey[100],
          contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFF00BFA6),
            foregroundColor: Colors.white,
            elevation: 0,
            padding: const EdgeInsets.symmetric(vertical: 16),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
            ),
            textStyle: const TextStyle(
              fontSize: 16,
              fontWeight: FontWeight.w600,
            ),
          ),
        ),
      ),
      home: StreamBuilder<User?>(
  stream: FirebaseAuth.instance.authStateChanges(),
  builder: (context, snapshot) {
    if (snapshot.connectionState == ConnectionState.waiting) {
      return const Center(child: CircularProgressIndicator());
    }
    if (snapshot.hasData) {
      return const HomeScreen();
    }
    return const OnboardingScreen();
        },
      ),
    );
  }
}
// import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'package:firebase_auth/firebase_auth.dart';
// import 'package:cloud_firestore/cloud_firestore.dart';
// import 'package:google_sign_in/google_sign_in.dart';
// import 'firebase_options.dart'; // This file will be generated by FlutterFire CLI

// // Main function with Firebase initialization
// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();
//   await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
//   );
//   runApp(const MyApp());
// }

// class MyApp extends StatelessWidget {
//   const MyApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       title: 'Food Delivery App',
//       debugShowCheckedModeBanner: false,
//       theme: ThemeData(
//         colorScheme: ColorScheme.fromSeed(
//           seedColor: const Color(0xFF00BFA6),
//           primary: const Color(0xFF00BFA6),
//         ),
//         fontFamily: 'Roboto',
//         inputDecorationTheme: InputDecorationTheme(
//           border: OutlineInputBorder(
//             borderRadius: BorderRadius.circular(8),
//             borderSide: BorderSide.none,
//           ),
//           filled: true,
//           fillColor: Colors.grey[100],
//           contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
//         ),
//         elevatedButtonTheme: ElevatedButtonThemeData(
//           style: ElevatedButton.styleFrom(
//             backgroundColor: const Color(0xFF00BFA6),
//             foregroundColor: Colors.white,
//             elevation: 0,
//             padding: const EdgeInsets.symmetric(vertical: 16),
//             shape: RoundedRectangleBorder(
//               borderRadius: BorderRadius.circular(8),
//             ),
//             textStyle: const TextStyle(
//               fontSize: 16,
//               fontWeight: FontWeight.w600,
//             ),
//           ),
//         ),
//       ),
//       home: StreamBuilder<User?>(
//         stream: FirebaseAuth.instance.authStateChanges(),
//         builder: (context, snapshot) {
//           // Check if user is logged in
//           if (snapshot.hasData) {
//             // Navigate to home screen if logged in
//             return const HomeScreen();
//           }
//           // Show onboarding if not logged in
//           return const OnboardingScreen();
//         },
//       ),
//     );
//   }
// }

// // Home Screen Placeholder (add this class)
// class HomeScreen extends StatelessWidget {
//   const HomeScreen({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: AppBar(
//         title: const Text('Food Delivery'),
//         actions: [
//           IconButton(
//             icon: const Icon(Icons.logout),
//             onPressed: () async {
//               await FirebaseAuth.instance.signOut();
//             },
//           ),
//         ],
//       ),
//       body: Center(
//         child: Column(
//           mainAxisAlignment: MainAxisAlignment.center,
//           children: [
//             Text(
//               'Welcome, ${FirebaseAuth.instance.currentUser?.displayName ?? 'User'}!',
//               style: const TextStyle(fontSize: 24),
//             ),
//             const SizedBox(height: 20),
//             Text('Email: ${FirebaseAuth.instance.currentUser?.email ?? 'No email'}'),
//           ],
//         ),
//       ),
//     );
//   }
// }

// // Onboarding Screen (remains mostly the same)
// class OnboardingScreen extends StatelessWidget {
//   const OnboardingScreen({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       backgroundColor: Colors.white,
//       body: SafeArea(
//         child: Column(
//           children: [
//             Expanded(
//               child: Padding(
//                 padding: const EdgeInsets.all(20.0),
//                 child: Column(
//                   mainAxisAlignment: MainAxisAlignment.center,
//                   children: [
//                     Expanded(
//                       child: Image.asset(
//                         'assets/images/scooter.png',
//                         fit: BoxFit.contain,
//                         errorBuilder: (context, error, stackTrace) {
//                           return Container(
//                             color: Colors.grey[200],
//                             child: const Center(
//                               child: Text(
//                                 'Delivery Person Image',
//                                 style: TextStyle(fontSize: 12),
//                               ),
//                             ),
//                           );
//                         },
//                       ),
//                     ),
//                     const SizedBox(height: 30),
//                     const Text(
//                       'Fast & easy food delivery',
//                       style: TextStyle(
//                         fontSize: 24,
//                         fontWeight: FontWeight.bold,
//                         color: Color(0xFF333333),
//                       ),
//                       textAlign: TextAlign.center,
//                     ),
//                     const SizedBox(height: 16),
//                     const Text(
//                       'Our fastest food delivery service can get you what you want in no time.',
//                       style: TextStyle(
//                         fontSize: 16,
//                         color: Color(0xFF666666),
//                       ),
//                       textAlign: TextAlign.center,
//                     ),
//                     const SizedBox(height: 60),
//                   ],
//                 ),
//               ),
//             ),
//             Padding(
//               padding: const EdgeInsets.symmetric(horizontal: 20),
//               child: Column(
//                 children: [
//                   // Page indicator dots
//                   Row(
//                     mainAxisAlignment: MainAxisAlignment.center,
//                     children: [
//                       Container(
//                         width: 25,
//                         height: 8,
//                         decoration: BoxDecoration(
//                           color: const Color(0xFFF8A92A),
//                           borderRadius: BorderRadius.circular(4),
//                         ),
//                       ),
//                       const SizedBox(width: 8),
//                       Container(
//                         width: 8,
//                         height: 8,
//                         decoration: BoxDecoration(
//                           color: const Color(0xFFD9D9D9),
//                           borderRadius: BorderRadius.circular(4),
//                         ),
//                       ),
//                       const SizedBox(width: 8),
//                       Container(
//                         width: 8,
//                         height: 8,
//                         decoration: BoxDecoration(
//                           color: const Color(0xFFD9D9D9),
//                           borderRadius: BorderRadius.circular(4),
//                         ),
//                       ),
//                     ],
//                   ),
//                   const SizedBox(height: 40),
//                   SizedBox(
//                     width: double.infinity,
//                     child: ElevatedButton(
//                       onPressed: () {
//                         Navigator.of(context).push(
//                           MaterialPageRoute(
//                             builder: (context) => const SignupScreen(),
//                           ),
//                         );
//                       },
//                       child: const Text('Get Started'),
//                     ),
//                   ),
//                   const SizedBox(height: 30),
//                 ],
//               ),
//             ),
//           ],
//         ),
//       ),
//     );
//   }
// }

// // Updated Signup Screen with Firebase
// class SignupScreen extends StatefulWidget {
//   const SignupScreen({super.key});

//   @override
//   State<SignupScreen> createState() => _SignupScreenState();
// }

// class _SignupScreenState extends State<SignupScreen> {
//   final _formKey = GlobalKey<FormState>();
//   final _nameController = TextEditingController();
//   final _phoneController = TextEditingController();
//   final _emailController = TextEditingController();
//   final _passwordController = TextEditingController();
//   bool _isLoading = false;

//   @override
//   void dispose() {
//     _nameController.dispose();
//     _phoneController.dispose();
//     _emailController.dispose();
//     _passwordController.dispose();
//     super.dispose();
//   }

//   // Method to sign up with email and password
//   Future<void> _signUp() async {
//     if (_formKey.currentState!.validate()) {
//       setState(() {
//         _isLoading = true;
//       });

//       try {
//         // Create user with email and password
//         final UserCredential userCredential = await FirebaseAuth.instance.createUserWithEmailAndPassword(
//           email: _emailController.text.trim(),
//           password: _passwordController.text,
//         );

//         // Update display name
//         await userCredential.user?.updateDisplayName(_nameController.text);

//         // Save additional user data to Firestore
//         await FirebaseFirestore.instance.collection('users').doc(userCredential.user!.uid).set({
//           'name': _nameController.text,
//           'email': _emailController.text.trim(),
//           'phone': _phoneController.text,
//           'createdAt': FieldValue.serverTimestamp(),
//         });

//         // Show success message
//         if (mounted) {
//           ScaffoldMessenger.of(context).showSnackBar(
//             const SnackBar(content: Text('Account created successfully!')),
//           );
          
//           // Navigate back to login or directly to the home page
//           Navigator.of(context).pushAndRemoveUntil(
//             MaterialPageRoute(builder: (context) => const HomeScreen()),
//             (route) => false,
//           );
//         }
//       } on FirebaseAuthException catch (e) {
//         String errorMessage = 'An error occurred during sign up';
        
//         if (e.code == 'weak-password') {
//           errorMessage = 'The password provided is too weak';
//         } else if (e.code == 'email-already-in-use') {
//           errorMessage = 'The account already exists for that email';
//         } else if (e.code == 'invalid-email') {
//           errorMessage = 'The email address is not valid';
//         }
        
//       if (!mounted) return; // Ensures that the State is still active

// ScaffoldMessenger.of(context).showSnackBar(
//   SnackBar(content: Text(errorMessage)),
// );



//       } catch (e) {
//   if (!mounted) return; // Ensure the widget is still in the widget tree

//   ScaffoldMessenger.of(context).showSnackBar(
//     SnackBar(content: Text('Error: ${e.toString()}')),
//   );
// }
//  finally {
//         if (mounted) {
//           setState(() {
//             _isLoading = false;
//           });
//         }
//       }
//     }
//   }

//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       backgroundColor: Colors.white,
//       appBar: AppBar(
//         backgroundColor: Colors.white,
//         elevation: 0,
//         leading: IconButton(
//           icon: const Icon(Icons.arrow_back, color: Colors.black),
//           onPressed: () => Navigator.of(context).pop(),
//         ),
//       ),
//       body: SafeArea(
//         child: SingleChildScrollView(
//           child: Padding(
//             padding: const EdgeInsets.all(20.0),
//             child: Form(
//               key: _formKey,
//               child: Column(
//                 crossAxisAlignment: CrossAxisAlignment.start,
//                 children: [
//                   const Text(
//                     'Create new account',
//                     style: TextStyle(
//                       fontSize: 24,
//                       fontWeight: FontWeight.bold,
//                       color: Colors.black,
//                     ),
//                   ),
//                   const SizedBox(height: 30),
//                   _buildTextField(
//                     controller: _nameController,
//                     hintText: 'Your Name',
//                     prefixIcon: Icons.person_outline,
//                     validator: (value) {
//                       if (value == null || value.isEmpty) {
//                         return 'Please enter your name';
//                       }
//                       return null;
//                     },
//                   ),
//                   const SizedBox(height: 16),
//                   _buildTextField(
//                     controller: _phoneController,
//                     hintText: 'Phone Number',
//                     prefixIcon: Icons.phone_android,
//                     keyboardType: TextInputType.phone,
//                     validator: (value) {
//                       if (value == null || value.isEmpty) {
//                         return 'Please enter your phone number';
//                       }
//                       return null;
//                     },
//                   ),
//                   const SizedBox(height: 16),
//                   _buildTextField(
//                     controller: _emailController,
//                     hintText: 'E-Mail',
//                     prefixIcon: Icons.email_outlined,
//                     keyboardType: TextInputType.emailAddress,
//                     validator: (value) {
//                       if (value == null || value.isEmpty) {
//                         return 'Please enter your email';
//                       }
//                       if (!RegExp(r'^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$').hasMatch(value)) {
//                         return 'Please enter a valid email';
//                       }
//                       return null;
//                     },
//                   ),
//                   const SizedBox(height: 16),
//                   _buildTextField(
//                     controller: _passwordController,
//                     hintText: 'Password',
//                     prefixIcon: Icons.lock_outline,
//                     obscureText: true,
//                     validator: (value) {
//                       if (value == null || value.isEmpty) {
//                         return 'Please enter your password';
//                       }
//                       if (value.length < 6) {
//                         return 'Password must be at least 6 characters long';
//                       }
//                       return null;
//                     },
//                   ),
//                   const SizedBox(height: 30),
//                   SizedBox(
//                     width: double.infinity,
//                     child: ElevatedButton(
//                       onPressed: _isLoading ? null : _signUp,
//                       child: _isLoading
//                           ? const SizedBox(
//                               height: 20,
//                               width: 20,
//                               child: CircularProgressIndicator(
//                                 color: Colors.white,
//                                 strokeWidth: 2,
//                               ),
//                             )
//                           : const Text('Sign Up'),
//                     ),
//                   ),
//                   const SizedBox(height: 20),
//                   Row(
//                     mainAxisAlignment: MainAxisAlignment.center,
//                     children: [
//                       const Text(
//                         'Already have an account?',
//                         style: TextStyle(color: Colors.black54),
//                       ),
//                       TextButton(
//                         onPressed: () {
//                           Navigator.of(context).push(
//                             MaterialPageRoute(
//                               builder: (context) => const LoginScreen(),
//                             ),
//                           );
//                         },
//                         child: const Text(
//                           'Log In',
//                           style: TextStyle(
//                             color: Color(0xFF00BFA6),
//                             fontWeight: FontWeight.bold,
//                           ),
//                         ),
//                       ),
//                     ],
//                   ),
//                   const SizedBox(height: 20),
//                   // Food illustration placeholder
//                   Center(
//                     child: Image.asset(
//                       'assets/images/food_gif.gif',
//                       height: 120,
//                       errorBuilder: (context, error, stackTrace) {
//                         return Container(
//                           height: 120,
//                           width: 200,
//                           color: Colors.grey[200],
//                           child: const Center(
//                             child: Text('Food Illustration'),
//                           ),
//                         );
//                       },
//                     ),
//                   ),
//                 ],
//               ),
//             ),
//           ),
//         ),
//       ),
//     );
//   }

//   Widget _buildTextField({
//     required TextEditingController controller,
//     required String hintText,
//     required IconData prefixIcon,
//     TextInputType keyboardType = TextInputType.text,
//     bool obscureText = false,
//     String? Function(String?)? validator,
//   }) {
//     return TextFormField(
//       controller: controller,
//       keyboardType: keyboardType,
//       obscureText: obscureText,
//       decoration: InputDecoration(
//         hintText: hintText,
//         prefixIcon: Icon(
//           prefixIcon,
//           color: Colors.grey,
//         ),
//         border: OutlineInputBorder(
//           borderRadius: BorderRadius.circular(8),
//           borderSide: BorderSide.none,
//         ),
//         filled: true,
//         fillColor: Colors.grey[100],
//       ),
//       validator: validator,
//     );
//   }
// }

// // Updated Login Screen with Firebase
// class LoginScreen extends StatefulWidget {
//   const LoginScreen({super.key});

//   @override
//   State<LoginScreen> createState() => _LoginScreenState();
// }

// class _LoginScreenState extends State<LoginScreen> {
//   final _formKey = GlobalKey<FormState>();
//   final _emailController = TextEditingController();
//   final _passwordController = TextEditingController();
//   bool _isLoading = false;
//   bool _obscurePassword = true;

//   final GoogleSignIn _googleSignIn = GoogleSignIn();

//   @override
//   void dispose() {
//     _emailController.dispose();
//     _passwordController.dispose();
//     super.dispose();
//   }

//   // Method to login with email and password
//   Future<void> _login() async {
//     if (_formKey.currentState!.validate()) {
//       setState(() {
//         _isLoading = true;
//       });

//       try {
//         // Sign in with email and password
//         await FirebaseAuth.instance.signInWithEmailAndPassword(
//           email: _emailController.text.trim(),
//           password: _passwordController.text,
//         );

//         // Navigate to home screen on successful login
//         if (mounted) {
//           Navigator.of(context).pushAndRemoveUntil(
//             MaterialPageRoute(builder: (context) => const HomeScreen()),
//             (route) => false,
//           );
//         }
//       } on FirebaseAuthException catch (e) {
//         String errorMessage = 'Login failed';
        
//         if (e.code == 'user-not-found') {
//           errorMessage = 'No user found for that email';
//         } else if (e.code == 'wrong-password') {
//           errorMessage = 'Wrong password provided';
//         } else if (e.code == 'invalid-email') {
//           errorMessage = 'The email address is not valid';
//         } else if (e.code == 'user-disabled') {
//           errorMessage = 'This user has been disabled';
//         }
        
//         if (!mounted) return; // Ensures the widget is still in the widget tree

// ScaffoldMessenger.of(context).showSnackBar(
//   SnackBar(content: Text(errorMessage)),
// );

//       } catch (e) {
//   if (!mounted) return; // Ensures the widget is still in the widget tree

//   ScaffoldMessenger.of(context).showSnackBar(
//     SnackBar(content: Text('Error: ${e.toString()}')),
//   );
// }
//  finally {
//         if (mounted) {
//           setState(() {
//             _isLoading = false;
//           });
//         }
//       }
//     }
//   }

//   // Method to handle Google Sign In
//   Future<void> _signInWithGoogle() async {
//     setState(() {
//       _isLoading = true;
//     });

//     try {
//       // Begin interactive sign in process
//       final GoogleSignInAccount? googleUser = await _googleSignIn.signIn();
      
//       if (googleUser == null) {
//         // User canceled the sign-in flow
//         setState(() {
//           _isLoading = false;
//         });
//         return;
//       }

//       // Obtain the auth details from the request
//       final GoogleSignInAuthentication googleAuth = await googleUser.authentication;

//       // Create a new credential
//       final credential = GoogleAuthProvider.credential(
//         accessToken: googleAuth.accessToken,
//         idToken: googleAuth.idToken,
//       );

//       // Sign in to Firebase with the Google credential
//       final UserCredential userCredential = 
//           await FirebaseAuth.instance.signInWithCredential(credential);
      
//       // Check if this is a new user
//       if (userCredential.additionalUserInfo?.isNewUser ?? false) {
//         // Save user data to Firestore for new users
//         await FirebaseFirestore.instance.collection('users').doc(userCredential.user!.uid).set({
//           'name': userCredential.user?.displayName,
//           'email': userCredential.user?.email,
//           'photoURL': userCredential.user?.photoURL,
//           'createdAt': FieldValue.serverTimestamp(),
//           'provider': 'google',
//         });
//       }

//       // Navigate to home screen on successful login
//       if (mounted) {
//         Navigator.of(context).pushAndRemoveUntil(
//           MaterialPageRoute(builder: (context) => const HomeScreen()),
//           (route) => false,
//         );
//       }
//     }catch (e) {
//   if (!mounted) return; // Ensures the widget is still in the widget tree

//   ScaffoldMessenger.of(context).showSnackBar(
//     SnackBar(content: Text('Google Sign-In failed: ${e.toString()}')),
//   );
// }
// finally {
//       if (mounted) {
//         setState(() {
//           _isLoading = false;
//         });
//       }
//     }
//   }

//   // Method to handle password reset
//   Future<void> _resetPassword() async {
//     final email = _emailController.text.trim();
    
//     if (email.isEmpty) {
//       ScaffoldMessenger.of(context).showSnackBar(
//         const SnackBar(content: Text('Please enter your email address')),
//       );
//       return;
//     }

//     try {
//       await FirebaseAuth.instance.sendPasswordResetEmail(email: email);
//       if (!mounted) return; // Ensures the widget is still in the widget tree

// ScaffoldMessenger.of(context).showSnackBar(
//   const SnackBar(content: Text('Password reset email sent!')),
// );

//     } on FirebaseAuthException catch (e) {
//       ScaffoldMessenger.of(context).showSnackBar(
//         SnackBar(content: Text('Error: ${e.message}')),
//       );
//     }
//   }

//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       backgroundColor: Colors.white,
//       appBar: AppBar(
//         backgroundColor: Colors.white,
//         elevation: 0,
//         leading: IconButton(
//           icon: const Icon(Icons.arrow_back, color: Colors.black),
//           onPressed: () => Navigator.of(context).pop(),
//         ),
//       ),
//       body: SafeArea(
//         child: SingleChildScrollView(
//           child: Padding(
//             padding: const EdgeInsets.all(20.0),
//             child: Form(
//               key: _formKey,
//               child: Column(
//                 crossAxisAlignment: CrossAxisAlignment.center,
//                 children: [
//                   // Mascot image placeholder
//                   Container(
//                     height: 120,
//                     width: 120,
//                     decoration: BoxDecoration(
//                       color: const Color(0xFFC75D56),
//                       borderRadius: BorderRadius.circular(60),
//                     ),
//                     child: Image.asset(
//                       'assets/images/mascot.png',
//                       errorBuilder: (context, error, stackTrace) {
//                         return const Center(
//                           child: Icon(
//                             Icons.face,
//                             size: 60,
//                             color: Colors.white,
//                           ),
//                         );
//                       },
//                     ),
//                   ),
//                   const SizedBox(height: 20),
//                   const Text(
//                     'Login',
//                     style: TextStyle(
//                       fontSize: 24,
//                       fontWeight: FontWeight.bold,
//                       color: Colors.black,
//                     ),
//                   ),
//                   const SizedBox(height: 30),
//                   _buildTextField(
//                     controller: _emailController,
//                     hintText: 'Your Email/Id',
//                     prefixIcon: Icons.email_outlined,
//                     keyboardType: TextInputType.emailAddress,
//                     validator: (value) {
//                       if (value == null || value.isEmpty) {
//                         return 'Please enter your email';
//                       }
//                       return null;
//                     },
//                   ),
//                   const SizedBox(height: 16),
//                   _buildPasswordField(),
//                   const SizedBox(height: 10),
//                   Align(
//                     alignment: Alignment.centerRight,
//                     child: TextButton(
//                       onPressed: _resetPassword,
//                       child: Row(
//                         mainAxisSize: MainAxisSize.min,
//                         children: [
//                           const Text(
//                             'Forgot Password',
//                             style: TextStyle(
//                               color: Colors.black54,
//                             ),
//                           ),
//                           const SizedBox(width: 4),
//                           Text(
//                             'Click Here',
//                             style: TextStyle(
//                               color: Theme.of(context).primaryColor,
//                               fontWeight: FontWeight.bold,
//                             ),
//                           ),
//                         ],
//                       ),
//                     ),
//                   ),
//                   const SizedBox(height: 30),
//                   SizedBox(
//                     width: double.infinity,
//                     child: ElevatedButton(
//                       onPressed: _isLoading ? null : _login,
//                       child: _isLoading
//                           ? const SizedBox(
//                               height: 20,
//                               width: 20,
//                               child: CircularProgressIndicator(
//                                 color: Colors.white,
//                                 strokeWidth: 2,
//                               ),
//                             )
//                           : const Text('Sign In'),
//                     ),
//                   ),
//                   const SizedBox(height: 20),
//                   SizedBox(
//                     width: double.infinity,
//                     child: ElevatedButton(
//                       onPressed: _isLoading ? null : _signInWithGoogle,
//                       style: ElevatedButton.styleFrom(
//                         backgroundColor: const Color(0xFF4A4A4A),
//                         foregroundColor: Colors.white,
//                       ),
//                       child: Row(
//                         mainAxisAlignment: MainAxisAlignment.center,
//                         children: [
//                           Container(
//                             height: 24,
//                             width: 24,
//                             decoration: const BoxDecoration(
//                               color: Colors.white,
//                               shape: BoxShape.circle,
//                             ),
//                             child: const Center(
//                               child: Text(
//                                 'G',
//                                 style: TextStyle(
//                                   color: Colors.red,
//                                   fontWeight: FontWeight.bold,
//                                 ),
//                               ),
//                             ),
//                           ),
//                           const SizedBox(width: 10),
//                           const Text('Continue with Google'),
//                         ],
//                       ),
//                     ),
//                   ),
//                 ],
//               ),
//             ),
//           ),
//         ),
//       ),
//     );
//   }

//   Widget _buildTextField({
//     required TextEditingController controller,
//     required String hintText,
//     required IconData prefixIcon,
//     TextInputType keyboardType = TextInputType.text,
//     String? Function(String?)? validator,
//   }) {
//     return TextFormField(
//       controller: controller,
//       keyboardType: keyboardType,
//       decoration: InputDecoration(
//         hintText: hintText,
//         prefixIcon: Icon(
//           prefixIcon,
//           color: Colors.grey,
//         ),
//         border: OutlineInputBorder(
//           borderRadius: BorderRadius.circular(8),
//           borderSide: BorderSide.none,
//         ),
//         filled: true,
//         fillColor: Colors.grey[100],
//       ),
//       validator: validator,
//     );
//   }

//   Widget _buildPasswordField() {
//     return TextFormField(
//       controller: _passwordController,
//       obscureText: _obscurePassword,
//       decoration: InputDecoration(
//         hintText: 'Your Password',
//         prefixIcon: const Icon(
//           Icons.lock_outline,
//           color: Colors.grey,
//         ),
//         suffixIcon: IconButton(
//           icon: Icon(
//             _obscurePassword ? Icons.visibility_outlined : Icons.visibility_off_outlined,
//             color: Colors.grey,
//           ),
//           onPressed: () {
//             setState(() {
//               _obscurePassword = !_obscurePassword;
//             });
//           },
//         ),
//         border: OutlineInputBorder(
//           borderRadius: BorderRadius.circular(8),
//           borderSide: BorderSide.none,
//         ),
//         filled: true,
//         fillColor: Colors.grey[100],
//       ),
//       validator: (value) {
//         if (value == null || value.isEmpty) {
//           return 'Please enter your password';
//         }
//         return null;
//       },
//     );
//   }
// }




// import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'package:firebase_auth/firebase_auth.dart';
// import 'package:cloud_firestore/cloud_firestore.dart';
// import 'package:google_sign_in/google_sign_in.dart';
// import 'firebase_options.dart'; // This file will be generated by FlutterFire CLI

// // Main function with Firebase initialization
// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();
//   await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
//   );
//   runApp(const MyApp());
// }

// class MyApp extends StatelessWidget {
//   const MyApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       title: 'Food Delivery App',
//       debugShowCheckedModeBanner: false,
//       theme: ThemeData(
//         colorScheme: ColorScheme.fromSeed(
//           seedColor: const Color(0xFF00BFA6),
//           primary: const Color(0xFF00BFA6),
//         ),
//         fontFamily: 'Roboto',
//         inputDecorationTheme: InputDecorationTheme(
//           border: OutlineInputBorder(
//             borderRadius: BorderRadius.circular(8),
//             borderSide: BorderSide.none,
//           ),
//           filled: true,
//           fillColor: Colors.grey[100],
//           contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
//         ),
//         elevatedButtonTheme: ElevatedButtonThemeData(
//           style: ElevatedButton.styleFrom(
//             backgroundColor: const Color(0xFF00BFA6),
//             foregroundColor: Colors.white,
//             elevation: 0,
//             padding: const EdgeInsets.symmetric(vertical: 16),
//             shape: RoundedRectangleBorder(
//               borderRadius: BorderRadius.circular(8),
//             ),
//             textStyle: const TextStyle(
//               fontSize: 16,
//               fontWeight: FontWeight.w600,
//             ),
//           ),
//         ),
//       ),
//       home: StreamBuilder<User?>(
//         stream: FirebaseAuth.instance.authStateChanges(),
//         builder: (context, snapshot) {
//           // Check if user is logged in
//           if (snapshot.hasData) {
//             // Navigate to home screen if logged in
//             return const HomeScreen();
//           }
//           // Show onboarding if not logged in
//           return const OnboardingScreen();
//         },
//       ),
//     );
//   }
// }

// // Home Screen Placeholder (add this class)
// class HomeScreen extends StatelessWidget {
//   const HomeScreen({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: AppBar(
//         title: const Text('Food Delivery'),
//         actions: [
//           IconButton(
//             icon: const Icon(Icons.logout),
//             onPressed: () async {
//               await FirebaseAuth.instance.signOut();
//             },
//           ),
//         ],
//       ),
//       body: Center(
//         child: Column(
//           mainAxisAlignment: MainAxisAlignment.center,
//           children: [
//             Text(
//               'Welcome, ${FirebaseAuth.instance.currentUser?.displayName ?? 'User'}!',
//               style: const TextStyle(fontSize: 24),
//             ),
//             const SizedBox(height: 20),
//             Text('Email: ${FirebaseAuth.instance.currentUser?.email ?? 'No email'}'),
//           ],
//         ),
//       ),
//     );
//   }
// }

// // Onboarding Screen (remains mostly the same)
// class OnboardingScreen extends StatelessWidget {
//   const OnboardingScreen({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       backgroundColor: Colors.white,
//       body: SafeArea(
//         child: Column(
//           children: [
//             Expanded(
//               child: Padding(
//                 padding: const EdgeInsets.all(20.0),
//                 child: Column(
//                   mainAxisAlignment: MainAxisAlignment.center,
//                   children: [
//                     Expanded(
//                       child: Image.asset(
//                         'assets/images/scooter.png',
//                         fit: BoxFit.contain,
//                         errorBuilder: (context, error, stackTrace) {
//                           return Container(
//                             color: Colors.grey[200],
//                             child: const Center(
//                               child: Text(
//                                 'Delivery Person Image',
//                                 style: TextStyle(fontSize: 12),
//                               ),
//                             ),
//                           );
//                         },
//                       ),
//                     ),
//                     const SizedBox(height: 30),
//                     const Text(
//                       'Fast & easy food delivery',
//                       style: TextStyle(
//                         fontSize: 24,
//                         fontWeight: FontWeight.bold,
//                         color: Color(0xFF333333),
//                       ),
//                       textAlign: TextAlign.center,
//                     ),
//                     const SizedBox(height: 16),
//                     const Text(
//                       'Our fastest food delivery service can get you what you want in no time.',
//                       style: TextStyle(
//                         fontSize: 16,
//                         color: Color(0xFF666666),
//                       ),
//                       textAlign: TextAlign.center,
//                     ),
//                     const SizedBox(height: 60),
//                   ],
//                 ),
//               ),
//             ),
//             Padding(
//               padding: const EdgeInsets.symmetric(horizontal: 20),
//               child: Column(
//                 children: [
//                   // Page indicator dots
//                   Row(
//                     mainAxisAlignment: MainAxisAlignment.center,
//                     children: [
//                       Container(
//                         width: 25,
//                         height: 8,
//                         decoration: BoxDecoration(
//                           color: const Color(0xFFF8A92A),
//                           borderRadius: BorderRadius.circular(4),
//                         ),
//                       ),
//                       const SizedBox(width: 8),
//                       Container(
//                         width: 8,
//                         height: 8,
//                         decoration: BoxDecoration(
//                           color: const Color(0xFFD9D9D9),
//                           borderRadius: BorderRadius.circular(4),
//                         ),
//                       ),
//                       const SizedBox(width: 8),
//                       Container(
//                         width: 8,
//                         height: 8,
//                         decoration: BoxDecoration(
//                           color: const Color(0xFFD9D9D9),
//                           borderRadius: BorderRadius.circular(4),
//                         ),
//                       ),
//                     ],
//                   ),
//                   const SizedBox(height: 40),
//                   SizedBox(
//                     width: double.infinity,
//                     child: ElevatedButton(
//                       onPressed: () {
//                         Navigator.of(context).push(
//                           MaterialPageRoute(
//                             builder: (context) => const SignupScreen(),
//                           ),
//                         );
//                       },
//                       child: const Text('Get Started'),
//                     ),
//                   ),
//                   const SizedBox(height: 30),
//                 ],
//               ),
//             ),
//           ],
//         ),
//       ),
//     );
//   }
// }

// // Updated Signup Screen with Firebase
// class SignupScreen extends StatefulWidget {
//   const SignupScreen({super.key});

//   @override
//   State<SignupScreen> createState() => _SignupScreenState();
// }

// class _SignupScreenState extends State<SignupScreen> {
//   final _formKey = GlobalKey<FormState>();
//   final _nameController = TextEditingController();
//   final _phoneController = TextEditingController();
//   final _emailController = TextEditingController();
//   final _passwordController = TextEditingController();
//   bool _isLoading = false;

//   @override
//   void dispose() {
//     _nameController.dispose();
//     _phoneController.dispose();
//     _emailController.dispose();
//     _passwordController.dispose();
//     super.dispose();
//   }

//   // Method to sign up with email and password
//   Future<void> _signUp() async {
//     if (_formKey.currentState!.validate()) {
//       setState(() {
//         _isLoading = true;
//       });

//       try {
//         // Create user with email and password
//         final UserCredential userCredential = await FirebaseAuth.instance.createUserWithEmailAndPassword(
//           email: _emailController.text.trim(),
//           password: _passwordController.text,
//         );

//         // Update display name
//         await userCredential.user?.updateDisplayName(_nameController.text);

//         // Save additional user data to Firestore
//         await FirebaseFirestore.instance.collection('users').doc(userCredential.user!.uid).set({
//           'name': _nameController.text,
//           'email': _emailController.text.trim(),
//           'phone': _phoneController.text,
//           'createdAt': FieldValue.serverTimestamp(),
//         });

//         // Show success message
//         if (mounted) {
//           ScaffoldMessenger.of(context).showSnackBar(
//             const SnackBar(content: Text('Account created successfully!')),
//           );
          
//           // Navigate back to login or directly to the home page
//           Navigator.of(context).pushAndRemoveUntil(
//             MaterialPageRoute(builder: (context) => const HomeScreen()),
//             (route) => false,
//           );
//         }
//       } on FirebaseAuthException catch (e) {
//         String errorMessage = 'An error occurred during sign up';
        
//         if (e.code == 'weak-password') {
//           errorMessage = 'The password provided is too weak';
//         } else if (e.code == 'email-already-in-use') {
//           errorMessage = 'The account already exists for that email';
//         } else if (e.code == 'invalid-email') {
//           errorMessage = 'The email address is not valid';
//         }
        
//       if (!mounted) return; // Ensures that the State is still active

// ScaffoldMessenger.of(context).showSnackBar(
//   SnackBar(content: Text(errorMessage)),
// );



//       } catch (e) {
//   if (!mounted) return; // Ensure the widget is still in the widget tree

//   ScaffoldMessenger.of(context).showSnackBar(
//     SnackBar(content: Text('Error: ${e.toString()}')),
//   );
// }
//  finally {
//         if (mounted) {
//           setState(() {
//             _isLoading = false;
//           });
//         }
//       }
//     }
//   }

//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       backgroundColor: Colors.white,
//       appBar: AppBar(
//         backgroundColor: Colors.white,
//         elevation: 0,
//         leading: IconButton(
//           icon: const Icon(Icons.arrow_back, color: Colors.black),
//           onPressed: () => Navigator.of(context).pop(),
//         ),
//       ),
//       body: SafeArea(
//         child: SingleChildScrollView(
//           child: Padding(
//             padding: const EdgeInsets.all(20.0),
//             child: Form(
//               key: _formKey,
//               child: Column(
//                 crossAxisAlignment: CrossAxisAlignment.start,
//                 children: [
//                   const Text(
//                     'Create new account',
//                     style: TextStyle(
//                       fontSize: 24,
//                       fontWeight: FontWeight.bold,
//                       color: Colors.black,
//                     ),
//                   ),
//                   const SizedBox(height: 30),
//                   _buildTextField(
//                     controller: _nameController,
//                     hintText: 'Your Name',
//                     prefixIcon: Icons.person_outline,
//                     validator: (value) {
//                       if (value == null || value.isEmpty) {
//                         return 'Please enter your name';
//                       }
//                       return null;
//                     },
//                   ),
//                   const SizedBox(height: 16),
//                   _buildTextField(
//                     controller: _phoneController,
//                     hintText: 'Phone Number',
//                     prefixIcon: Icons.phone_android,
//                     keyboardType: TextInputType.phone,
//                     validator: (value) {
//                       if (value == null || value.isEmpty) {
//                         return 'Please enter your phone number';
//                       }
//                       return null;
//                     },
//                   ),
//                   const SizedBox(height: 16),
//                   _buildTextField(
//                     controller: _emailController,
//                     hintText: 'E-Mail',
//                     prefixIcon: Icons.email_outlined,
//                     keyboardType: TextInputType.emailAddress,
//                     validator: (value) {
//                       if (value == null || value.isEmpty) {
//                         return 'Please enter your email';
//                       }
//                       if (!RegExp(r'^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$').hasMatch(value)) {
//                         return 'Please enter a valid email';
//                       }
//                       return null;
//                     },
//                   ),
//                   const SizedBox(height: 16),
//                   _buildTextField(
//                     controller: _passwordController,
//                     hintText: 'Password',
//                     prefixIcon: Icons.lock_outline,
//                     obscureText: true,
//                     validator: (value) {
//                       if (value == null || value.isEmpty) {
//                         return 'Please enter your password';
//                       }
//                       if (value.length < 6) {
//                         return 'Password must be at least 6 characters long';
//                       }
//                       return null;
//                     },
//                   ),
//                   const SizedBox(height: 30),
//                   SizedBox(
//                     width: double.infinity,
//                     child: ElevatedButton(
//                       onPressed: _isLoading ? null : _signUp,
//                       child: _isLoading
//                           ? const SizedBox(
//                               height: 20,
//                               width: 20,
//                               child: CircularProgressIndicator(
//                                 color: Colors.white,
//                                 strokeWidth: 2,
//                               ),
//                             )
//                           : const Text('Sign Up'),
//                     ),
//                   ),
//                   const SizedBox(height: 20),
//                   Row(
//                     mainAxisAlignment: MainAxisAlignment.center,
//                     children: [
//                       const Text(
//                         'Already have an account?',
//                         style: TextStyle(color: Colors.black54),
//                       ),
//                       TextButton(
//                         onPressed: () {
//                           Navigator.of(context).push(
//                             MaterialPageRoute(
//                               builder: (context) => const LoginScreen(),
//                             ),
//                           );
//                         },
//                         child: const Text(
//                           'Log In',
//                           style: TextStyle(
//                             color: Color(0xFF00BFA6),
//                             fontWeight: FontWeight.bold,
//                           ),
//                         ),
//                       ),
//                     ],
//                   ),
//                   const SizedBox(height: 20),
//                   // Food illustration placeholder
//                   Center(
//                     child: Image.asset(
//                       'assets/images/food_gif.gif',
//                       height: 120,
//                       errorBuilder: (context, error, stackTrace) {
//                         return Container(
//                           height: 120,
//                           width: 200,
//                           color: Colors.grey[200],
//                           child: const Center(
//                             child: Text('Food Illustration'),
//                           ),
//                         );
//                       },
//                     ),
//                   ),
//                 ],
//               ),
//             ),
//           ),
//         ),
//       ),
//     );
//   }

//   Widget _buildTextField({
//     required TextEditingController controller,
//     required String hintText,
//     required IconData prefixIcon,
//     TextInputType keyboardType = TextInputType.text,
//     bool obscureText = false,
//     String? Function(String?)? validator,
//   }) {
//     return TextFormField(
//       controller: controller,
//       keyboardType: keyboardType,
//       obscureText: obscureText,
//       decoration: InputDecoration(
//         hintText: hintText,
//         prefixIcon: Icon(
//           prefixIcon,
//           color: Colors.grey,
//         ),
//         border: OutlineInputBorder(
//           borderRadius: BorderRadius.circular(8),
//           borderSide: BorderSide.none,
//         ),
//         filled: true,
//         fillColor: Colors.grey[100],
//       ),
//       validator: validator,
//     );
//   }
// }

// // Updated Login Screen with Firebase
// class LoginScreen extends StatefulWidget {
//   const LoginScreen({super.key});

//   @override
//   State<LoginScreen> createState() => _LoginScreenState();
// }

// class _LoginScreenState extends State<LoginScreen> {
//   final _formKey = GlobalKey<FormState>();
//   final _emailController = TextEditingController();
//   final _passwordController = TextEditingController();
//   bool _isLoading = false;
//   bool _obscurePassword = true;

//   final GoogleSignIn _googleSignIn = GoogleSignIn();

//   @override
//   void dispose() {
//     _emailController.dispose();
//     _passwordController.dispose();
//     super.dispose();
//   }

//   // Method to login with email and password
//   Future<void> _login() async {
//     if (_formKey.currentState!.validate()) {
//       setState(() {
//         _isLoading = true;
//       });

//       try {
//         // Sign in with email and password
//         await FirebaseAuth.instance.signInWithEmailAndPassword(
//           email: _emailController.text.trim(),
//           password: _passwordController.text,
//         );

//         // Navigate to home screen on successful login
//         if (mounted) {
//           Navigator.of(context).pushAndRemoveUntil(
//             MaterialPageRoute(builder: (context) => const HomeScreen()),
//             (route) => false,
//           );
//         }
//       } on FirebaseAuthException catch (e) {
//         String errorMessage = 'Login failed';
        
//         if (e.code == 'user-not-found') {
//           errorMessage = 'No user found for that email';
//         } else if (e.code == 'wrong-password') {
//           errorMessage = 'Wrong password provided';
//         } else if (e.code == 'invalid-email') {
//           errorMessage = 'The email address is not valid';
//         } else if (e.code == 'user-disabled') {
//           errorMessage = 'This user has been disabled';
//         }
        
//         if (!mounted) return; // Ensures the widget is still in the widget tree

// ScaffoldMessenger.of(context).showSnackBar(
//   SnackBar(content: Text(errorMessage)),
// );

//       } catch (e) {
//   if (!mounted) return; // Ensures the widget is still in the widget tree

//   ScaffoldMessenger.of(context).showSnackBar(
//     SnackBar(content: Text('Error: ${e.toString()}')),
//   );
// }
//  finally {
//         if (mounted) {
//           setState(() {
//             _isLoading = false;
//           });
//         }
//       }
//     }
//   }

//   // Method to handle Google Sign In
//   Future<void> _signInWithGoogle() async {
//     setState(() {
//       _isLoading = true;
//     });

//     try {
//       // Begin interactive sign in process
//       final GoogleSignInAccount? googleUser = await _googleSignIn.signIn();
      
//       if (googleUser == null) {
//         // User canceled the sign-in flow
//         setState(() {
//           _isLoading = false;
//         });
//         return;
//       }

//       // Obtain the auth details from the request
//       final GoogleSignInAuthentication googleAuth = await googleUser.authentication;

//       // Create a new credential
//       final credential = GoogleAuthProvider.credential(
//         accessToken: googleAuth.accessToken,
//         idToken: googleAuth.idToken,
//       );

//       // Sign in to Firebase with the Google credential
//       final UserCredential userCredential = 
//           await FirebaseAuth.instance.signInWithCredential(credential);
      
//       // Check if this is a new user
//       if (userCredential.additionalUserInfo?.isNewUser ?? false) {
//         // Save user data to Firestore for new users
//         await FirebaseFirestore.instance.collection('users').doc(userCredential.user!.uid).set({
//           'name': userCredential.user?.displayName,
//           'email': userCredential.user?.email,
//           'photoURL': userCredential.user?.photoURL,
//           'createdAt': FieldValue.serverTimestamp(),
//           'provider': 'google',
//         });
//       }

//       // Navigate to home screen on successful login
//       if (mounted) {
//         Navigator.of(context).pushAndRemoveUntil(
//           MaterialPageRoute(builder: (context) => const HomeScreen()),
//           (route) => false,
//         );
//       }
//     }catch (e) {
//   if (!mounted) return; // Ensures the widget is still in the widget tree

//   ScaffoldMessenger.of(context).showSnackBar(
//     SnackBar(content: Text('Google Sign-In failed: ${e.toString()}')),
//   );
// }
// finally {
//       if (mounted) {
//         setState(() {
//           _isLoading = false;
//         });
//       }
//     }
//   }

//   // Method to handle password reset
//   Future<void> _resetPassword() async {
//     final email = _emailController.text.trim();
    
//     if (email.isEmpty) {
//       ScaffoldMessenger.of(context).showSnackBar(
//         const SnackBar(content: Text('Please enter your email address')),
//       );
//       return;
//     }

//     try {
//       await FirebaseAuth.instance.sendPasswordResetEmail(email: email);
//       if (!mounted) return; // Ensures the widget is still in the widget tree

// ScaffoldMessenger.of(context).showSnackBar(
//   const SnackBar(content: Text('Password reset email sent!')),
// );

//     } on FirebaseAuthException catch (e) {
//       ScaffoldMessenger.of(context).showSnackBar(
//         SnackBar(content: Text('Error: ${e.message}')),
//       );
//     }
//   }

//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       backgroundColor: Colors.white,
//       appBar: AppBar(
//         backgroundColor: Colors.white,
//         elevation: 0,
//         leading: IconButton(
//           icon: const Icon(Icons.arrow_back, color: Colors.black),
//           onPressed: () => Navigator.of(context).pop(),
//         ),
//       ),
//       body: SafeArea(
//         child: SingleChildScrollView(
//           child: Padding(
//             padding: const EdgeInsets.all(20.0),
//             child: Form(
//               key: _formKey,
//               child: Column(
//                 crossAxisAlignment: CrossAxisAlignment.center,
//                 children: [
//                   // Mascot image placeholder
//                   Container(
//                     height: 120,
//                     width: 120,
//                     decoration: BoxDecoration(
//                       color: const Color(0xFFC75D56),
//                       borderRadius: BorderRadius.circular(60),
//                     ),
//                     child: Image.asset(
//                       'assets/images/mascot.png',
//                       errorBuilder: (context, error, stackTrace) {
//                         return const Center(
//                           child: Icon(
//                             Icons.face,
//                             size: 60,
//                             color: Colors.white,
//                           ),
//                         );
//                       },
//                     ),
//                   ),
//                   const SizedBox(height: 20),
//                   const Text(
//                     'Login',
//                     style: TextStyle(
//                       fontSize: 24,
//                       fontWeight: FontWeight.bold,
//                       color: Colors.black,
//                     ),
//                   ),
//                   const SizedBox(height: 30),
//                   _buildTextField(
//                     controller: _emailController,
//                     hintText: 'Your Email/Id',
//                     prefixIcon: Icons.email_outlined,
//                     keyboardType: TextInputType.emailAddress,
//                     validator: (value) {
//                       if (value == null || value.isEmpty) {
//                         return 'Please enter your email';
//                       }
//                       return null;
//                     },
//                   ),
//                   const SizedBox(height: 16),
//                   _buildPasswordField(),
//                   const SizedBox(height: 10),
//                   Align(
//                     alignment: Alignment.centerRight,
//                     child: TextButton(
//                       onPressed: _resetPassword,
//                       child: Row(
//                         mainAxisSize: MainAxisSize.min,
//                         children: [
//                           const Text(
//                             'Forgot Password',
//                             style: TextStyle(
//                               color: Colors.black54,
//                             ),
//                           ),
//                           const SizedBox(width: 4),
//                           Text(
//                             'Click Here',
//                             style: TextStyle(
//                               color: Theme.of(context).primaryColor,
//                               fontWeight: FontWeight.bold,
//                             ),
//                           ),
//                         ],
//                       ),
//                     ),
//                   ),
//                   const SizedBox(height: 30),
//                   SizedBox(
//                     width: double.infinity,
//                     child: ElevatedButton(
//                       onPressed: _isLoading ? null : _login,
//                       child: _isLoading
//                           ? const SizedBox(
//                               height: 20,
//                               width: 20,
//                               child: CircularProgressIndicator(
//                                 color: Colors.white,
//                                 strokeWidth: 2,
//                               ),
//                             )
//                           : const Text('Sign In'),
//                     ),
//                   ),
//                   const SizedBox(height: 20),
//                   SizedBox(
//                     width: double.infinity,
//                     child: ElevatedButton(
//                       onPressed: _isLoading ? null : _signInWithGoogle,
//                       style: ElevatedButton.styleFrom(
//                         backgroundColor: const Color(0xFF4A4A4A),
//                         foregroundColor: Colors.white,
//                       ),
//                       child: Row(
//                         mainAxisAlignment: MainAxisAlignment.center,
//                         children: [
//                           Container(
//                             height: 24,
//                             width: 24,
//                             decoration: const BoxDecoration(
//                               color: Colors.white,
//                               shape: BoxShape.circle,
//                             ),
//                             child: const Center(
//                               child: Text(
//                                 'G',
//                                 style: TextStyle(
//                                   color: Colors.red,
//                                   fontWeight: FontWeight.bold,
//                                 ),
//                               ),
//                             ),
//                           ),
//                           const SizedBox(width: 10),
//                           const Text('Continue with Google'),
//                         ],
//                       ),
//                     ),
//                   ),
//                 ],
//               ),
//             ),
//           ),
//         ),
//       ),
//     );
//   }

//   Widget _buildTextField({
//     required TextEditingController controller,
//     required String hintText,
//     required IconData prefixIcon,
//     TextInputType keyboardType = TextInputType.text,
//     String? Function(String?)? validator,
//   }) {
//     return TextFormField(
//       controller: controller,
//       keyboardType: keyboardType,
//       decoration: InputDecoration(
//         hintText: hintText,
//         prefixIcon: Icon(
//           prefixIcon,
//           color: Colors.grey,
//         ),
//         border: OutlineInputBorder(
//           borderRadius: BorderRadius.circular(8),
//           borderSide: BorderSide.none,
//         ),
//         filled: true,
//         fillColor: Colors.grey[100],
//       ),
//       validator: validator,
//     );
//   }

//   Widget _buildPasswordField() {
//     return TextFormField(
//       controller: _passwordController,
//       obscureText: _obscurePassword,
//       decoration: InputDecoration(
//         hintText: 'Your Password',
//         prefixIcon: const Icon(
//           Icons.lock_outline,
//           color: Colors.grey,
//         ),
//         suffixIcon: IconButton(
//           icon: Icon(
//             _obscurePassword ? Icons.visibility_outlined : Icons.visibility_off_outlined,
//             color: Colors.grey,
//           ),
//           onPressed: () {
//             setState(() {
//               _obscurePassword = !_obscurePassword;
//             });
//           },
//         ),
//         border: OutlineInputBorder(
//           borderRadius: BorderRadius.circular(8),
//           borderSide: BorderSide.none,
//         ),
//         filled: true,
//         fillColor: Colors.grey[100],
//       ),
//       validator: (value) {
//         if (value == null || value.isEmpty) {
//           return 'Please enter your password';
//         }
//         return null;
//       },
//     );
//   }
// }